language: go
sudo: false
go:
  - 1.16

env:
  global:
    - TFLIB=libtensorflow-cpu-linux-x86_64-2.4.0.tar.gz
    - LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$TRAVIS_BUILD_DIR/lib
    - LIBRARY_PATH=$TRAVIS_BUILD_DIR/lib

install:
  - mkdir -p $TRAVIS_BUILD_DIR/lib
  - wget https://storage.googleapis.com/tensorflow/libtensorflow/$TFLIB
  - tar xfz $TFLIB
  - LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$PWD/lib
  - LIBRARY_PATH=$PWD/lib
  - WDIR=$PWD
  - git clone https://github.com/vkuznet/TFaaS
  - cd TFaaS/src/Go
  - make
  - ls
