name: Build

on:
  push:
    tags:
      - '*.*.*'

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: ^1.20

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Build
      run: |
        mkdir -p tensorflow
        cd tensorflow
        TFLIB=libtensorflow-cpu-linux-x86_64-2.11.0.tar.gz
        curl -ksLO https://storage.googleapis.com/tensorflow/libtensorflow/$TFLIB
        tar xfz $TFLIB
        export LD_LIBRARY_PATH=$PWD/lib
        export LIBRARY_PATH=$PWD/lib
        export CGO_CPPFLAGS="-I$PWD/include"
        export CGO_CFLAGS="-I$PWD/include"
        cd -
        cd src/Go
        make

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false

    - name: Upload binary
      id: upload-auth-proxy-server
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: src/Go/tfaas
        asset_name: tfaas
        asset_content_type: application/octet-stream

    - name: Get the Ref
      id: get-ref
      uses: ankitvgupta/ref-to-tag-action@master
      with:
        ref: ${{ github.ref }}
        head_ref: ${{ github.head_ref }}

    - name: Build image
      run: |
        docker build . --tag docker.pkg.github.com/veknet/tfaas
        docker tag docker.pkg.github.com/veknet/tfaas/tfaas registry.cern.ch/cmsweb/tfaas

    - name: Login to registry.cern.ch
      uses: docker/login-action@v1.6.0
      with:
        registry: registry.cern.ch
        username: ${{ secrets.CERN_LOGIN }}
        password: ${{ secrets.CERN_TOKEN }}

    - name: Publish image to registry.cern.ch
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.CERN_LOGIN }}
        password: ${{ secrets.CERN_TOKEN }}
        registry: registry.cern.ch
        repository: cmsweb/tfaas
        tag_with_ref: true
      
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        load: true
        tags: veknet/tfaas:${{steps.get-ref.outputs.tag}}
    - run: docker push veknet/tfaas:${{steps.get-ref.outputs.tag}}
